version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    expose:
      - 4000
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '4000:4000'
  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/secrets-manager
    restart: always
    command: bash -c "npm install --only=prod && npm i nodemon -g -D && npm run debug"
    volumes:
      - ./dist/:/usr/src/secrets-manager/dist/
      - ./package.json:/usr/src/secrets-manager/package.json
    ports:
      - '3000:3000'
      - '9222:9222'
    links:
      - mongo
